### ISSUE TITLE
How were the datasets generated?

### ISSUE THREAD

**Issue by mihirkale815** [DwaraknathT/GSoC-19#24]
Hi! The README mentions that the datasets are based on WebNLG. Can you provide references to the German and Russian datasets?

**Comment by DwaraknathT** [comment]
Hi @mihirkale815 sorry for the late reply, The German and Russian corpora can be found here. 
Ger - https://github.com/ThiagoCF05/webnlg
Rus - https://gitlab.com/shimorina/webnlg-dataset, or you may contact @ThiagoCF05  for the Russian corpus
